"""
Unit tests for LLM-first metric extraction with deterministic verification (Change 2).

Asserts:
1. Exactly one batched LLM call per document on the happy path.
2. Table selection picks only primary statements (drops all other tables).
3. Hallucinated values are rejected by the verbatim grounding check.
4. Balance-sheet mismatch triggers exactly one retry for the failing statement.
5. Unit scaling in Python is applied correctly (millions -> base units; EPS untouched).
"""

from decimal import Decimal
from unittest.mock import AsyncMock

import pytest

from app.llm.client import llm_client
from app.models.metrics import RawMetricItem
from app.models.parser import ParsedTable
from app.services.metric_extractor import (
    ExtractedMetricList,
    MetricExtractionService,
    PrimaryStatementType,
)


@pytest.fixture
def sample_tables() -> list[ParsedTable]:
    """Sample parsed tables representing a 10-K filing with 3 primary statements and 2 footnote tables."""
    ops_table = ParsedTable(
        table_index=0,
        page_number=45,
        section_path="Item 8. Financial Statements > Consolidated Statements of Operations",
        markdown_content="""
# Consolidated Statements of Operations
(In millions, except per share amounts)
| Line Item | 2024 | 2023 |
| Total net sales | $ 383,285 | $ 394,328 |
| Cost of sales | $ 214,137 | $ 223,546 |
| Gross margin | $ 169,148 | $ 170,782 |
| Operating expenses | $ 54,847 | $ 51,345 |
| Operating income | $ 114,301 | $ 119,437 |
| Net income | $ 96,995 | $ 99,803 |
| Diluted earnings per share | $ 6.13 | $ 6.11 |
""".strip(),
        num_rows=8,
        num_cols=3,
    )

    bs_table = ParsedTable(
        table_index=1,
        page_number=46,
        section_path="Item 8. Financial Statements > Consolidated Balance Sheets",
        markdown_content="""
# Consolidated Balance Sheets
(In millions)
| Line Item | 2024 | 2023 |
| Cash and cash equivalents | $ 29,965 | $ 29,965 |
| Total assets | $ 352,583 | $ 352,583 |
| Total liabilities | $ 290,437 | $ 290,437 |
| Total stockholders' equity | $ 62,146 | $ 62,146 |
""".strip(),
        num_rows=5,
        num_cols=3,
    )

    cf_table = ParsedTable(
        table_index=2,
        page_number=47,
        section_path="Item 8. Financial Statements > Consolidated Statements of Cash Flows",
        markdown_content="""
# Consolidated Statements of Cash Flows
(In millions)
| Line Item | 2024 | 2023 |
| Cash generated by operating activities | $ 110,543 | $ 122,151 |
| Payments for property, plant and equipment | $ 10,959 | $ 10,708 |
""".strip(),
        num_rows=4,
        num_cols=3,
    )

    footnote_table = ParsedTable(
        table_index=3,
        page_number=62,
        section_path="Note 12. Segment Information and Geographic Data",
        markdown_content="""
| Region | Americas | Europe | Greater China |
| Revenue | 162,560 | 94,294 | 72,559 |
""".strip(),
        num_rows=3,
        num_cols=4,
    )

    commitments_table = ParsedTable(
        table_index=4,
        page_number=70,
        section_path="Note 15. Commitments and Contingencies",
        markdown_content="""
| Term | 2025 | 2026 | Thereafter |
| Operating Leases | 1,500 | 1,200 | 4,000 |
""".strip(),
        num_rows=3,
        num_cols=4,
    )

    return [ops_table, bs_table, cf_table, footnote_table, commitments_table]


def test_table_selection_drops_non_primary_tables(sample_tables: list[ParsedTable]) -> None:
    """Check 1: Only primary statements are selected; footnote & segment tables are dropped."""
    selected = MetricExtractionService.select_primary_statement_tables(sample_tables)

    assert len(selected) == 3
    assert PrimaryStatementType.OPERATIONS in selected
    assert PrimaryStatementType.BALANCE_SHEET in selected
    assert PrimaryStatementType.CASH_FLOWS in selected
    assert selected[PrimaryStatementType.OPERATIONS].table_index == 0
    assert selected[PrimaryStatementType.BALANCE_SHEET].table_index == 1
    assert selected[PrimaryStatementType.CASH_FLOWS].table_index == 2


@pytest.mark.asyncio
async def test_happy_path_single_batched_call_and_unit_scaling(
    monkeypatch: pytest.MonkeyPatch, sample_tables: list[ParsedTable]
) -> None:
    """Check 2, 5 & Happy Path: Exactly one batched LLM call per document and unit scaling applied."""
    happy_metrics = [
        RawMetricItem(
            metric_name="total_revenue",
            value=Decimal("383285"),
            unit="USD_millions",
            source_page=45,
        ),
        RawMetricItem(
            metric_name="cost_of_revenue",
            value=Decimal("214137"),
            unit="USD_millions",
            source_page=45,
        ),
        RawMetricItem(
            metric_name="gross_profit", value=Decimal("169148"), unit="USD_millions", source_page=45
        ),
        RawMetricItem(
            metric_name="operating_expenses",
            value=Decimal("54847"),
            unit="USD_millions",
            source_page=45,
        ),
        RawMetricItem(
            metric_name="operating_income",
            value=Decimal("114301"),
            unit="USD_millions",
            source_page=45,
        ),
        RawMetricItem(
            metric_name="net_income", value=Decimal("96995"), unit="USD_millions", source_page=45
        ),
        RawMetricItem(
            metric_name="diluted_eps", value=Decimal("6.13"), unit="USD_per_share", source_page=45
        ),
        RawMetricItem(
            metric_name="cash_and_equivalents",
            value=Decimal("29965"),
            unit="USD_millions",
            source_page=46,
        ),
        RawMetricItem(
            metric_name="total_assets", value=Decimal("352583"), unit="USD_millions", source_page=46
        ),
        RawMetricItem(
            metric_name="total_liabilities",
            value=Decimal("290437"),
            unit="USD_millions",
            source_page=46,
        ),
        RawMetricItem(
            metric_name="stockholders_equity",
            value=Decimal("62146"),
            unit="USD_millions",
            source_page=46,
        ),
        RawMetricItem(
            metric_name="operating_cash_flow",
            value=Decimal("110543"),
            unit="USD_millions",
            source_page=47,
        ),
        RawMetricItem(
            metric_name="capital_expenditures",
            value=Decimal("10959"),
            unit="USD_millions",
            source_page=47,
        ),
    ]

    mock_generate = AsyncMock(return_value=ExtractedMetricList(metrics=happy_metrics))
    monkeypatch.setattr(llm_client, "generate_structured", mock_generate)

    results = await MetricExtractionService.extract_all_metrics(
        tables=sample_tables, form_type="10-K", fiscal_year=2024
    )

    # 1. Assert exactly ONE LLM call on happy path
    assert mock_generate.call_count == 1

    # 2. Assert all metrics are grounded & verified
    for m in results:
        assert m.verified is True
        assert m.low_confidence is False

    # 3. Assert unit scaling in Python: millions scaled by 1,000,000; EPS untouched
    metrics_by_name = {m.metric_name: m for m in results}
    assert metrics_by_name["total_revenue"].value == Decimal("383285000000")
    assert metrics_by_name["total_revenue"].unit == "USD_units"
    assert metrics_by_name["gross_profit"].value == Decimal("169148000000")
    assert metrics_by_name["total_assets"].value == Decimal("352583000000")
    # EPS must NOT be scaled
    assert metrics_by_name["diluted_eps"].value == Decimal("6.13")


@pytest.mark.asyncio
async def test_hallucinated_value_rejected_by_grounding_check(
    monkeypatch: pytest.MonkeyPatch, sample_tables: list[ParsedTable]
) -> None:
    """Check 3: A hallucinated value not appearing in the source table is flagged as verified=False."""
    hallucinated_metrics = [
        RawMetricItem(
            metric_name="total_revenue",
            value=Decimal("999999"),
            unit="USD_millions",
            source_page=45,
        ),
        RawMetricItem(
            metric_name="gross_profit", value=Decimal("169148"), unit="USD_millions", source_page=45
        ),
    ]

    mock_generate = AsyncMock(return_value=ExtractedMetricList(metrics=hallucinated_metrics))
    monkeypatch.setattr(llm_client, "generate_structured", mock_generate)

    results = await MetricExtractionService.extract_all_metrics(
        tables=sample_tables, form_type="10-K", fiscal_year=2024
    )

    metrics_by_name = {m.metric_name: m for m in results}

    # 999999 does not appear anywhere in table text -> verified=False, low_confidence=True
    assert metrics_by_name["total_revenue"].verified is False
    assert metrics_by_name["total_revenue"].low_confidence is True

    # 169148 appeared in table text -> verified=True
    assert metrics_by_name["gross_profit"].verified is True


@pytest.mark.asyncio
async def test_balance_sheet_mismatch_triggers_one_retry(
    monkeypatch: pytest.MonkeyPatch, sample_tables: list[ParsedTable]
) -> None:
    """Check 4: Balance sheet mismatch triggers exactly one retry for the failing statement."""
    # First call: mismatch (Assets 400000 != Liabilities 290437 + Equity 62146)
    mismatched_metrics = [
        RawMetricItem(
            metric_name="total_assets", value=Decimal("400000"), unit="USD_millions", source_page=46
        ),
        RawMetricItem(
            metric_name="total_liabilities",
            value=Decimal("290437"),
            unit="USD_millions",
            source_page=46,
        ),
        RawMetricItem(
            metric_name="stockholders_equity",
            value=Decimal("62146"),
            unit="USD_millions",
            source_page=46,
        ),
    ]

    # Second call (retry): corrected (Assets 352583 == 290437 + 62146)
    corrected_bs_metrics = [
        RawMetricItem(
            metric_name="total_assets", value=Decimal("352583"), unit="USD_millions", source_page=46
        ),
        RawMetricItem(
            metric_name="total_liabilities",
            value=Decimal("290437"),
            unit="USD_millions",
            source_page=46,
        ),
        RawMetricItem(
            metric_name="stockholders_equity",
            value=Decimal("62146"),
            unit="USD_millions",
            source_page=46,
        ),
    ]

    mock_generate = AsyncMock(
        side_effect=[
            ExtractedMetricList(metrics=mismatched_metrics),
            ExtractedMetricList(metrics=corrected_bs_metrics),
        ]
    )
    monkeypatch.setattr(llm_client, "generate_structured", mock_generate)

    results = await MetricExtractionService.extract_all_metrics(
        tables=sample_tables, form_type="10-K", fiscal_year=2024
    )

    # Assert exactly 2 calls: initial call + 1 retry
    assert mock_generate.call_count == 2

    metrics_by_name = {m.metric_name: m for m in results}
    # After retry, the corrected value is stored and verified
    assert metrics_by_name["total_assets"].value == Decimal("352583000000")
    assert metrics_by_name["total_assets"].verified is True
    assert metrics_by_name["total_assets"].low_confidence is False


@pytest.mark.asyncio
async def test_balance_sheet_mismatch_still_failing_after_retry_not_dropped(
    monkeypatch: pytest.MonkeyPatch, sample_tables: list[ParsedTable]
) -> None:
    """Check 4: If mismatch persists after retry, store metric with verified=False, low_confidence=True instead of dropping."""
    mismatched_metrics = [
        RawMetricItem(
            metric_name="total_assets", value=Decimal("400000"), unit="USD_millions", source_page=46
        ),
        RawMetricItem(
            metric_name="total_liabilities",
            value=Decimal("290437"),
            unit="USD_millions",
            source_page=46,
        ),
        RawMetricItem(
            metric_name="stockholders_equity",
            value=Decimal("62146"),
            unit="USD_millions",
            source_page=46,
        ),
    ]

    # Both initial and retry fail the accounting check
    mock_generate = AsyncMock(
        side_effect=[
            ExtractedMetricList(metrics=mismatched_metrics),
            ExtractedMetricList(metrics=mismatched_metrics),
        ]
    )
    monkeypatch.setattr(llm_client, "generate_structured", mock_generate)

    results = await MetricExtractionService.extract_all_metrics(
        tables=sample_tables, form_type="10-K", fiscal_year=2024
    )

    # Exactly 2 calls (retries once, does not loop infinitely)
    assert mock_generate.call_count == 2

    metrics_by_name = {m.metric_name: m for m in results}
    # Failing metrics are preserved, flagged as low_confidence and verified=False
    assert "total_assets" in metrics_by_name
    assert metrics_by_name["total_assets"].verified is False
    assert metrics_by_name["total_assets"].low_confidence is True
