"""
Structured Financial Metric Extraction Service using OpenRouter.

WHY STRUCTURED EXTRACTION OVER FREE-FORM TEXT (AGENT.md §8):
1. Financial reports use different line item names ('Net Sales' vs 'Total Revenue',
   'Additions to Property & Equipment' vs 'Capital Expenditures').
2. We provide an explicit Pydantic schema and accounting standard alias maps to OpenRouter models
   (US GAAP for 10-K/10-Q, IFRS for 20-F), forcing the model to normalize variations to standard snake_case keys.
3. Strict Provenance: Every single metric MUST cite its source_page (ADR-2).
"""

from pydantic import BaseModel, Field

from app.llm.client import llm_client
from app.models.metrics import RawMetricItem
from app.models.parser import ParsedTable


class ExtractedMetricList(BaseModel):
    """Container schema for structured LLM extraction output."""

    metrics: list[RawMetricItem] = Field(
        default_factory=list,
        description="List of extracted raw financial line items with page provenance",
    )


# Standard Line Item Alias Mappings
US_GAAP_ALIASES: dict[str, list[str]] = {
    "total_revenue": [
        "Total net sales",
        "Total revenue",
        "Revenues",
        "Net sales",
        "Revenue",
        "Total revenues, net",
    ],
    "cost_of_revenue": [
        "Cost of sales",
        "Cost of goods sold",
        "Cost of revenue",
        "Cost of products",
        "Cost of services",
    ],
    "gross_profit": ["Gross margin", "Gross profit"],
    "operating_expenses": ["Total operating expenses", "Operating expenses"],
    "operating_income": [
        "Operating income",
        "Income from operations",
        "Operating profit",
    ],
    "net_income": [
        "Net income",
        "Net earnings",
        "Net income attributable to common shareholders",
    ],
    "diluted_eps": [
        "Diluted earnings per share",
        "Diluted net income per share",
        "Diluted EPS",
    ],
    "total_assets": ["Total assets"],
    "total_liabilities": ["Total liabilities"],
    "stockholders_equity": [
        "Total shareholders' equity",
        "Total stockholders' equity",
        "Shareholders' equity",
        "Stockholders' equity",
        "Total equity",
    ],
    "cash_and_equivalents": [
        "Cash and cash equivalents",
        "Cash & cash equivalents",
        "Cash and equivalents",
    ],
    "operating_cash_flow": [
        "Cash generated by operating activities",
        "Cash provided by operating activities",
        "Net cash provided by operating activities",
        "Net cash from operating activities",
    ],
    "capital_expenditures": [
        "Payments for property, plant and equipment",
        "Additions to property, plant and equipment",
        "Capital expenditures",
        "Purchase of property and equipment",
    ],
}

IFRS_ALIASES: dict[str, list[str]] = {
    "total_revenue": ["Revenue", "Revenues", "Turnover", "Total revenue"],
    "cost_of_revenue": ["Cost of sales", "Cost of revenue"],
    "gross_profit": ["Gross profit"],
    "operating_expenses": ["Operating costs", "Total operating expenses"],
    "operating_income": [
        "Operating profit",
        "Results from operating activities",
        "Operating income",
    ],
    "net_income": [
        "Profit for the year",
        "Profit for the period",
        "Net profit",
        "Net income",
        "Profit attributable to owners of the parent",
    ],
    "diluted_eps": [
        "Diluted earnings per share",
        "Diluted profit per share",
        "Diluted EPS",
    ],
    "total_assets": ["Total assets", "Total non-current assets and current assets"],
    "total_liabilities": [
        "Total liabilities",
        "Total non-current liabilities and current liabilities",
    ],
    "stockholders_equity": [
        "Total equity",
        "Equity attributable to owners of the parent",
        "Total equity and reserves",
        "Share capital and reserves",
    ],
    "cash_and_equivalents": [
        "Cash and cash equivalents",
        "Cash and balances with banks",
        "Cash and balances with central banks",
    ],
    "operating_cash_flow": [
        "Cash flows from operating activities",
        "Net cash from operating activities",
        "Cash generated from operations",
    ],
    "capital_expenditures": [
        "Purchase of property, plant and equipment",
        "Capital expenditure",
        "Additions to property, plant and equipment",
    ],
}


class MetricExtractionService:
    """Service that coordinates LLM-based extraction of the 13 core financial metrics."""

    @classmethod
    def get_alias_map(cls, form_type: str = "10-K") -> dict[str, list[str]]:
        """Selects the alias map based on the filing form type (US GAAP vs IFRS)."""
        if (form_type or "").upper() == "20-F":
            return IFRS_ALIASES
        return US_GAAP_ALIASES

    @classmethod
    def get_system_prompt(cls, form_type: str = "10-K") -> str:
        """Constructs a context-aware system prompt with accounting standard alias hints."""
        is_ifrs = (form_type or "").upper() == "20-F"
        standard_name = (
            "IFRS (International Financial Reporting Standards)" if is_ifrs else "US GAAP"
        )
        alias_map = cls.get_alias_map(form_type)

        aliases_formatted = "\n".join(
            f"- {metric}: {', '.join(aliases)}" for metric, aliases in alias_map.items()
        )

        return f"""You are a precise financial data extraction analyst.
Analyze the provided financial statement table from an SEC {form_type} filing adhering to {standard_name}.

Extract any of the following 13 target metrics if they appear in the table:
- Income Statement: total_revenue, cost_of_revenue, gross_profit, operating_expenses, operating_income, net_income, diluted_eps
- Balance Sheet: total_assets, total_liabilities, stockholders_equity, cash_and_equivalents
- Cash Flow: operating_cash_flow, capital_expenditures

Standard Line Item Aliases for {standard_name}:
{aliases_formatted}

RULES:
1. Return EXACT raw numeric values in the specified unit (e.g. if reported in millions, 383,285 represents 383285).
2. Parentheses indicate negative numbers: (1,234) -> -1234.
3. You MUST provide the exact source_page number provided in the table metadata.
4. If a metric is NOT in the table, DO NOT invent or guess it; simply omit it.
"""

    @classmethod
    async def extract_metrics_from_table(
        cls, table: ParsedTable, form_type: str = "10-K"
    ) -> list[RawMetricItem]:
        """
        Extracts financial line items from a single parsed table.

        Args:
            table: ParsedTable instance with markdown content and page provenance.
            form_type: SEC filing form type ('10-K', '10-Q', '20-F').

        Returns:
            List of validated RawMetricItem instances.
        """
        user_prompt = f"""
Table Metadata:
- Page Number: {table.page_number}
- Section: {table.section_path}

Table Markdown:
{table.markdown_content}
"""

        messages = [
            {"role": "system", "content": cls.get_system_prompt(form_type)},
            {"role": "user", "content": user_prompt},
        ]

        try:
            result: ExtractedMetricList = await llm_client.generate_structured(
                messages=messages,
                schema=ExtractedMetricList,
                temperature=0.0,
            )
            # Ensure each metric carries the table's source_page and chunk reference
            for metric in result.metrics:
                if metric.source_page <= 0:
                    metric.source_page = table.page_number
                metric.source_chunk_id = f"p{table.page_number}_t{table.table_index}"
            return result.metrics
        except Exception as exc:
            print(
                f"⚠️ [Extraction] Failed to extract metrics from table on page {table.page_number}: {exc}"
            )
            return []

    @classmethod
    async def extract_all_metrics(
        cls, tables: list[ParsedTable], form_type: str = "10-K"
    ) -> list[RawMetricItem]:
        """
        Iterates over all candidate tables in a document and extracts financial metrics.
        Deduplicates by metric_name, keeping the latest/most specific statement figure.
        """
        extracted_map: dict[str, RawMetricItem] = {}

        for table in tables:
            # Quick heuristic: Skip tiny non-financial tables (< 3 rows)
            if table.num_rows < 3:
                continue

            items = await cls.extract_metrics_from_table(table, form_type=form_type)
            for item in items:
                # Upsert by metric_name
                extracted_map[item.metric_name] = item

        return list(extracted_map.values())
